

services:
  nlp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: palash-mtb-mle-nlp
    working_dir: /app
    volumes:
      - .:/app
    command: python nlp_models/test_indictrans2_hi_sat.py